// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvu5mc93NvykwMcLQdCsHkbDyZHf14jNA',
    appId: '1:373532453592:web:94aec44a804f9613bb05ad',
    messagingSenderId: '373532453592',
    projectId: 'mis-project-4eb27',
    authDomain: 'mis-project-4eb27.firebaseapp.com',
    storageBucket: 'mis-project-4eb27.firebasestorage.app',
    measurementId: 'G-XNCGQB1XYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFbPJH6qSSmQlBMliRIHNh01LH9MyW-M',
    appId: '1:373532453592:android:eafca4ee64e09628bb05ad',
    messagingSenderId: '373532453592',
    projectId: 'mis-project-4eb27',
    storageBucket: 'mis-project-4eb27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsfyi4WHKAv_YeZPoJGkpiMlwrSlnx4Qg',
    appId: '1:373532453592:ios:6a20db477f8f9b16bb05ad',
    messagingSenderId: '373532453592',
    projectId: 'mis-project-4eb27',
    storageBucket: 'mis-project-4eb27.firebasestorage.app',
    iosBundleId: 'com.example.mish2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsfyi4WHKAv_YeZPoJGkpiMlwrSlnx4Qg',
    appId: '1:373532453592:ios:6a20db477f8f9b16bb05ad',
    messagingSenderId: '373532453592',
    projectId: 'mis-project-4eb27',
    storageBucket: 'mis-project-4eb27.firebasestorage.app',
    iosBundleId: 'com.example.mish2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvu5mc93NvykwMcLQdCsHkbDyZHf14jNA',
    appId: '1:373532453592:web:f634a8c30723a612bb05ad',
    messagingSenderId: '373532453592',
    projectId: 'mis-project-4eb27',
    authDomain: 'mis-project-4eb27.firebaseapp.com',
    storageBucket: 'mis-project-4eb27.firebasestorage.app',
    measurementId: 'G-MCCLX8DRD1',
  );
}
